"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 10:03:52.452619
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'OWNER', 'ADMIN', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('CITIZEN', 'OWNER', 'ADMIN')", name='user_role'),
    sa.CheckConstraint("role IN ('CITIZEN', 'OWNER', 'ADMIN')", name=op.f('ck_users_user_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY', name='category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OUT_OF_STOCK', 'CLOSED', 'BUSY', 'MAINTENANCE', name='location_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('queue_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'NOT_APPLICABLE', name='queue_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("approval_status IN ('PENDING', 'APPROVED', 'REJECTED')", name='approval_status'),
    sa.CheckConstraint("approval_status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_locations_approval_status')),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name='category'),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name=op.f('ck_locations_category')),
    sa.CheckConstraint("queue_level IN ('LOW', 'MEDIUM', 'HIGH', 'NOT_APPLICABLE')", name='queue_level'),
    sa.CheckConstraint("queue_level IN ('LOW', 'MEDIUM', 'HIGH', 'NOT_APPLICABLE')", name=op.f('ck_locations_queue_level')),
    sa.CheckConstraint("status IN ('AVAILABLE', 'OUT_OF_STOCK', 'CLOSED', 'BUSY', 'MAINTENANCE')", name='location_status'),
    sa.CheckConstraint("status IN ('AVAILABLE', 'OUT_OF_STOCK', 'CLOSED', 'BUSY', 'MAINTENANCE')", name=op.f('ck_locations_location_status')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_locations_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_locations_longitude_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_locations_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('id', 'category', name='uq_locations_id_category')
    )
    op.create_index(op.f('ix_locations_approval_status'), 'locations', ['approval_status'], unique=False)
    op.create_index(op.f('ix_locations_category'), 'locations', ['category'], unique=False)
    op.create_index('ix_locations_lat_lon', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('ix_locations_owner_id'), 'locations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_locations_queue_level'), 'locations', ['queue_level'], unique=False)
    op.create_index(op.f('ix_locations_status'), 'locations', ['status'], unique=False)
    op.create_table('ev_station_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY', name='category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('total_plugs', sa.Integer(), nullable=False),
    sa.Column('occupied_plugs', sa.Integer(), nullable=False),
    sa.Column('charging_type', sa.Enum('AC_SLOW', 'DC_FAST', 'MIXED', name='charging_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint("category = 'EV_CHARGING'", name=op.f('ck_ev_station_details_category_is_ev')),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name='category'),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name=op.f('ck_ev_station_details_category')),
    sa.CheckConstraint("charging_type IN ('AC_SLOW', 'DC_FAST', 'MIXED')", name='charging_type'),
    sa.CheckConstraint("charging_type IN ('AC_SLOW', 'DC_FAST', 'MIXED')", name=op.f('ck_ev_station_details_charging_type')),
    sa.CheckConstraint('estimated_wait_minutes >= 0', name=op.f('ck_ev_station_details_wait_non_negative')),
    sa.CheckConstraint('occupied_plugs <= total_plugs', name=op.f('ck_ev_station_details_occupied_lte_total')),
    sa.CheckConstraint('occupied_plugs >= 0', name=op.f('ck_ev_station_details_occupied_plugs_non_negative')),
    sa.CheckConstraint('total_plugs >= 0', name=op.f('ck_ev_station_details_total_plugs_non_negative')),
    sa.ForeignKeyConstraint(['location_id', 'category'], ['locations.id', 'locations.category'], name='fk_ev_station_details_location_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ev_station_details'))
    )
    op.create_index(op.f('ix_ev_station_details_location_id'), 'ev_station_details', ['location_id'], unique=True)
    op.create_table('location_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('update_type', sa.Enum('CREATED', 'PROFILE', 'STATUS', 'QUEUE', 'STOCK', 'MUSEUM', 'EV_AVAILABILITY', 'PHARMACY_INVENTORY', 'MODERATION', 'DELETED', name='update_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("update_type IN ('CREATED', 'PROFILE', 'STATUS', 'QUEUE', 'STOCK', 'MUSEUM', 'EV_AVAILABILITY', 'PHARMACY_INVENTORY', 'MODERATION', 'DELETED')", name='update_type'),
    sa.CheckConstraint("update_type IN ('CREATED', 'PROFILE', 'STATUS', 'QUEUE', 'STOCK', 'MUSEUM', 'EV_AVAILABILITY', 'PHARMACY_INVENTORY', 'MODERATION', 'DELETED')", name=op.f('ck_location_updates_update_type')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_location_updates_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_location_updates_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_updates'))
    )
    op.create_index('ix_location_updates_location_created', 'location_updates', ['location_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_location_updates_location_id'), 'location_updates', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_updates_updated_by'), 'location_updates', ['updated_by'], unique=False)
    op.create_table('museum_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY', name='category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('historical_description', sa.Text(), nullable=True),
    sa.Column('guide_available', sa.Boolean(), nullable=False),
    sa.Column('guide_url', sa.String(length=500), nullable=True),
    sa.Column('guide_content_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("category = 'MUSEUM_MONUMENT'", name=op.f('ck_museum_details_category_is_museum')),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name='category'),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name=op.f('ck_museum_details_category')),
    sa.ForeignKeyConstraint(['location_id', 'category'], ['locations.id', 'locations.category'], name='fk_museum_details_location_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_museum_details'))
    )
    op.create_index(op.f('ix_museum_details_location_id'), 'museum_details', ['location_id'], unique=True)
    op.create_table('pharmacy_medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY', name='category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('prescription_required', sa.Boolean(), nullable=False),
    sa.Column('last_stock_update', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category = 'PHARMACY'", name=op.f('ck_pharmacy_medicines_category_is_pharmacy')),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name='category'),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name=op.f('ck_pharmacy_medicines_category')),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name=op.f('ck_pharmacy_medicines_quantity_non_negative')),
    sa.ForeignKeyConstraint(['location_id', 'category'], ['locations.id', 'locations.category'], name='fk_pharmacy_medicines_location_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_medicines')),
    sa.UniqueConstraint('location_id', 'name_key', name='uq_pharmacy_medicines_location_name')
    )
    op.create_index(op.f('ix_pharmacy_medicines_location_id'), 'pharmacy_medicines', ['location_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_medicines_name_key'), 'pharmacy_medicines', ['name_key'], unique=False)
    op.create_table('ration_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY', name='category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('rice', sa.Enum('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', name='rice_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('wheat', sa.Enum('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', name='wheat_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('dal', sa.Enum('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', name='dal_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('other_items', sa.JSON(), nullable=False),
    sa.CheckConstraint("category = 'RATION_SHOP'", name=op.f('ck_ration_stock_category_is_ration')),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name='category'),
    sa.CheckConstraint("category IN ('RATION_SHOP', 'MUSEUM_MONUMENT', 'EV_CHARGING', 'PHARMACY')", name=op.f('ck_ration_stock_category')),
    sa.CheckConstraint("dal IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name='dal_level'),
    sa.CheckConstraint("dal IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name=op.f('ck_ration_stock_dal_level')),
    sa.CheckConstraint("rice IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name='rice_level'),
    sa.CheckConstraint("rice IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name=op.f('ck_ration_stock_rice_level')),
    sa.CheckConstraint("wheat IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name='wheat_level'),
    sa.CheckConstraint("wheat IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name=op.f('ck_ration_stock_wheat_level')),
    sa.ForeignKeyConstraint(['location_id', 'category'], ['locations.id', 'locations.category'], name='fk_ration_stock_location_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ration_stock'))
    )
    op.create_index(op.f('ix_ration_stock_location_id'), 'ration_stock', ['location_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ration_stock_location_id'), table_name='ration_stock')
    op.drop_table('ration_stock')
    op.drop_index(op.f('ix_pharmacy_medicines_name_key'), table_name='pharmacy_medicines')
    op.drop_index(op.f('ix_pharmacy_medicines_location_id'), table_name='pharmacy_medicines')
    op.drop_table('pharmacy_medicines')
    op.drop_index(op.f('ix_museum_details_location_id'), table_name='museum_details')
    op.drop_table('museum_details')
    op.drop_index(op.f('ix_location_updates_updated_by'), table_name='location_updates')
    op.drop_index(op.f('ix_location_updates_location_id'), table_name='location_updates')
    op.drop_index('ix_location_updates_location_created', table_name='location_updates')
    op.drop_table('location_updates')
    op.drop_index(op.f('ix_ev_station_details_location_id'), table_name='ev_station_details')
    op.drop_table('ev_station_details')
    op.drop_index(op.f('ix_locations_status'), table_name='locations')
    op.drop_index(op.f('ix_locations_queue_level'), table_name='locations')
    op.drop_index(op.f('ix_locations_owner_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index('ix_locations_lat_lon', table_name='locations')
    op.drop_index(op.f('ix_locations_category'), table_name='locations')
    op.drop_index(op.f('ix_locations_approval_status'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
